# Use an official Python image as base
FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /FantasySgpSystem

ENV RUNNING_IN_DOCKER=true \
    PYTHONPATH=/FantasySgpSystem

# Install dependencies for Chrome & Selenium
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget curl unzip gnupg ca-certificates fonts-liberation \
    libappindicator3-1 libasound2 libgbm-dev libgtk-3-0 \
    libnss3 lsb-release xdg-utils jq \
 && rm -rf /var/lib/apt/lists/*

# Install pinned Chrome
RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_146.0.7680.164-1_amd64.deb \
 && dpkg -i google-chrome-stable_146.0.7680.164-1_amd64.deb || apt-get -fy install \
 && rm google-chrome-stable_146.0.7680.164-1_amd64.deb

# Install pinned ChromeDriver
RUN wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/146.0.7680.165/linux64/chromedriver-linux64.zip \
 && unzip chromedriver-linux64.zip \
 && mv chromedriver /usr/local/bin/chromedriver \
 && chmod +x /usr/local/bin/chromedriver \
 && rm -rf chromedriver-linux64.zip

    
# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy import files
COPY . .
# Expose the port Flask runs on
EXPOSE 5000

RUN mkdir -p /downloads

COPY preseason_entrypoint.sh ./preseason_entrypoint.sh
RUN sed -i 's/\r$//' ./preseason_entrypoint.sh && chmod +x ./preseason_entrypoint.sh
ENTRYPOINT ["./preseason_entrypoint.sh"]

